In [1]:
import pandas as pd

In [2]:
df=pd.read_csv('Heart.csv')

In [3]:
df

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,299,45,1,typical,110,264,0,0,132,0,1.2,2,0.0,reversable,Yes
299,300,68,1,asymptomatic,144,193,1,0,141,0,3.4,2,2.0,reversable,Yes
300,301,57,1,asymptomatic,130,131,0,0,115,1,1.2,2,1.0,reversable,Yes
301,302,57,0,nontypical,130,236,0,2,174,0,0.0,2,1.0,normal,Yes
302,303,38,1,nonanginal,138,175,0,0,173,0,0.0,1,NaN,normal,No

In [4]:
df.head()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,1,63,1,typical,145,233,1,2,150,0,2.3,3,0.0,fixed,No
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
2,3,67,1,asymptomatic,120,229,0,2,129,1,2.6,2,2.0,reversable,Yes
3,4,37,1,nonanginal,130,250,0,0,187,0,3.5,3,0.0,normal,No
4,5,41,0,nontypical,130,204,0,2,172,0,1.4,1,0.0,normal,No

### Find shape of the Data

In [5]:
df.shape

(303, 15)

### Find missing values

In [6]:
df.isna()

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
0,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
299,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
300,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
301,False,False,False,False,False,False,False,False,False,False,False,False,False,False,False
302,False,False,False,False,False,False,False,False,False,False,False,False,True,False,False

In [7]:
df.isna().sum()

Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
Ca            4
Thal          2
AHD           0
dtype: int64

In [8]:
df.isna().sum().sort_values(ascending = False)

Ca            4
Thal          2
Unnamed: 0    0
Age           0
Sex           0
ChestPain     0
RestBP        0
Chol          0
Fbs           0
RestECG       0
MaxHR         0
ExAng         0
Oldpeak       0
Slope         0
AHD           0
dtype: int64

### Find datatye of each column

In [9]:
df.dtypes

Unnamed: 0      int64
Age             int64
Sex             int64
ChestPain      object
RestBP          int64
Chol            int64
Fbs             int64
RestECG         int64
MaxHR           int64
ExAng           int64
Oldpeak       float64
Slope           int64
Ca            float64
Thal           object
AHD            object
dtype: object

### Finding out zeros

In [10]:
df.columns

Index(['Unnamed: 0', 'Age', 'Sex', 'ChestPain', 'RestBP', 'Chol', 'Fbs',
       'RestECG', 'MaxHR', 'ExAng', 'Oldpeak', 'Slope', 'Ca', 'Thal', 'AHD'],
      dtype='object')

In [11]:
for col in df.columns:
    print(f'\n No. of zeros in  {col} : {(df[col]==0).sum()}')

 No. of zeros in  Unnamed: 0 : 0

 No. of zeros in  Age : 0

 No. of zeros in  Sex : 97

 No. of zeros in  ChestPain : 0

 No. of zeros in  RestBP : 0

 No. of zeros in  Chol : 0

 No. of zeros in  Fbs : 258

 No. of zeros in  RestECG : 151

 No. of zeros in  MaxHR : 0

 No. of zeros in  ExAng : 204

 No. of zeros in  Oldpeak : 99

 No. of zeros in  Slope : 0

 No. of zeros in  Ca : 176

 No. of zeros in  Thal : 0

 No. of zeros in  AHD : 0

### Mean age of patients

In [12]:
print("Mean Age : ",df['Age'].mean())

Mean Age :  54.43894389438944

### Divide dataset into 2 dataframes randomly with 75% in trainig and 25% in testing

In [13]:
train=df.sample(frac=0.75)

In [14]:
train

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
236,237,56,1,asymptomatic,130,283,1,2,103,1,1.6,3,0.0,reversable,Yes
283,284,35,1,nontypical,122,192,0,0,174,0,0.0,1,0.0,normal,No
256,257,67,0,asymptomatic,106,223,0,0,142,0,0.3,1,2.0,normal,No
212,213,41,1,nonanginal,130,214,0,2,168,0,2.0,2,0.0,normal,No
229,230,66,1,asymptomatic,112,212,0,2,132,1,0.1,1,1.0,normal,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
294,295,63,0,asymptomatic,124,197,0,0,136,1,0.0,2,0.0,normal,Yes
132,133,29,1,nontypical,130,204,0,2,202,0,0.0,1,0.0,normal,No
65,66,60,1,asymptomatic,145,282,0,2,142,1,2.8,2,2.0,reversable,Yes
110,111,61,0,asymptomatic,145,307,0,2,146,1,1.0,2,0.0,reversable,Yes
52,53,44,1,asymptomatic,112,290,0,2,153,0,0.0,1,1.0,normal,Yes

In [15]:
train.index

Int64Index([236, 283, 256, 212, 229, 131,  71,  41,  31, 169,
            ...
            295, 118,  82,   3, 121, 294, 132,  65, 110,  52],
           dtype='int64', length=227)

In [16]:
test = df.drop(train.index)

In [17]:
test

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
8,9,63,1,asymptomatic,130,254,0,2,147,0,1.4,2,1.0,reversable,Yes
12,13,56,1,nonanginal,130,256,1,2,142,1,0.6,2,1.0,fixed,Yes
15,16,57,1,nonanginal,150,168,0,0,174,0,1.6,1,0.0,normal,No
16,17,48,1,nontypical,110,229,0,0,168,0,1.0,3,0.0,reversable,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,283,55,0,asymptomatic,128,205,0,1,130,1,2.0,2,1.0,reversable,Yes
285,286,58,1,asymptomatic,114,318,0,1,140,0,4.4,3,3.0,fixed,Yes
286,287,58,0,asymptomatic,170,225,1,2,146,1,2.8,2,2.0,fixed,Yes
287,288,58,1,nontypical,125,220,0,0,144,0,0.4,2,NaN,reversable,No
296,297,59,1,asymptomatic,164,176,1,2,90,0,1.0,2,2.0,fixed,Yes

In [18]:
test.index

Int64Index([  1,   8,  12,  15,  16,  25,  29,  36,  37,  40,  42,  43,  46,
             47,  53,  54,  59,  60,  68,  70,  72,  80,  83,  87,  88,  91,
            101, 102, 105, 106, 108, 109, 115, 124, 126, 127, 133, 135, 138,
            139, 140, 143, 147, 148, 150, 151, 162, 163, 165, 179, 183, 185,
            186, 195, 196, 203, 213, 215, 218, 221, 222, 224, 225, 234, 240,
            242, 253, 263, 270, 276, 280, 282, 285, 286, 287, 296],
           dtype='int64')

### Now extract only Age, Sex, ChestPain ,RestBP, Chol. Randomly divide dataset in training(75%) and testing(25%)

In [19]:
subset = df[['Age','Sex','ChestPain','RestBP','Chol']]
subset

     Age  Sex     ChestPain  RestBP  Chol
0     63    1       typical     145   233
1     67    1  asymptomatic     160   286
2     67    1  asymptomatic     120   229
3     37    1    nonanginal     130   250
4     41    0    nontypical     130   204
..   ...  ...           ...     ...   ...
298   45    1       typical     110   264
299   68    1  asymptomatic     144   193
300   57    1  asymptomatic     130   131
301   57    0    nontypical     130   236
302   38    1    nonanginal     138   175

[303 rows x 5 columns]

In [20]:
train1 = subset.sample(frac=0.75)

In [21]:
train1

     Age  Sex     ChestPain  RestBP  Chol
241   41    0    nontypical     126   306
207   50    1  asymptomatic     144   200
130   54    1    nonanginal     120   258
28    43    1  asymptomatic     150   247
113   43    0  asymptomatic     132   341
..   ...  ...           ...     ...   ...
274   59    1       typical     134   204
140   59    1    nontypical     140   221
117   35    0  asymptomatic     138   183
108   61    1  asymptomatic     120   260
24    60    1  asymptomatic     130   206

[227 rows x 5 columns]

In [22]:
train1.index

Int64Index([241, 207, 130,  28, 113, 183, 234, 145, 294,  63,
            ...
            275,  51, 243, 211, 109, 274, 140, 117, 108,  24],
           dtype='int64', length=227)

test = subset.drop(train1.index)

In [23]:
test

,Unnamed: 0,Age,Sex,ChestPain,RestBP,Chol,Fbs,RestECG,MaxHR,ExAng,Oldpeak,Slope,Ca,Thal,AHD
1,2,67,1,asymptomatic,160,286,0,2,108,1,1.5,2,3.0,normal,Yes
8,9,63,1,asymptomatic,130,254,0,2,147,0,1.4,2,1.0,reversable,Yes
12,13,56,1,nonanginal,130,256,1,2,142,1,0.6,2,1.0,fixed,Yes
15,16,57,1,nonanginal,150,168,0,0,174,0,1.6,1,0.0,normal,No
16,17,48,1,nontypical,110,229,0,0,168,0,1.0,3,0.0,reversable,Yes
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
282,283,55,0,asymptomatic,128,205,0,1,130,1,2.0,2,1.0,reversable,Yes
285,286,58,1,asymptomatic,114,318,0,1,140,0,4.4,3,3.0,fixed,Yes
286,287,58,0,asymptomatic,170,225,1,2,146,1,2.8,2,2.0,fixed,Yes
287,288,58,1,nontypical,125,220,0,0,144,0,0.4,2,NaN,reversable,No
296,297,59,1,asymptomatic,164,176,1,2,90,0,1.0,2,2.0,fixed,Yes

In [24]:
test.index

Int64Index([  1,   8,  12,  15,  16,  25,  29,  36,  37,  40,  42,  43,  46,
             47,  53,  54,  59,  60,  68,  70,  72,  80,  83,  87,  88,  91,
            101, 102, 105, 106, 108, 109, 115, 124, 126, 127, 133, 135, 138,
            139, 140, 143, 147, 148, 150, 151, 162, 163, 165, 179, 183, 185,
            186, 195, 196, 203, 213, 215, 218, 221, 222, 224, 225, 234, 240,
            242, 253, 263, 270, 276, 280, 282, 285, 286, 287, 296],
           dtype='int64')